//
// Created by ahmed on 1/14/17.
//

#ifndef UDPSOCKETLIB_PROTOCOLMSGID_H
#define UDPSOCKETLIB_PROTOCOLMSGID_H

#define ID_HAND_SHAKE -1
#define ID_GO_REDIRECT -2
#define ID_REDIRECT_SUCC -3
#define ID_REDIRECT_ACK -4
#define ID_FILE_NAME -5
#define ID_PCKT_COUNT -6

#endif //UDPSOCKETLIB_PROTOCOLMSGID_H
